"""
report_generator.py
====================
Assembles a business report (Markdown) combining:
  - Hard metrics from eda_analysis.py (ground truth)
  - Detected patterns from insight_generator.py (rule-based)
  - Claude-written executive narrative tying it together

This is the "weekly report" / "business summary" deliverable. It never
lets Claude compute a number — it only narrates numbers this script
already calculated, exactly like business_analyst_assistant.py.

Run:
    python report_generator.py --data-dir /path/to/csvs --out report.md
"""

import sys
import argparse
from pathlib import Path
from datetime import date

sys.path.append(str(Path(__file__).resolve().parent.parent / "Python"))
sys.path.append(str(Path(__file__).resolve().parent.parent / "EDA"))
import etl_pipeline  # noqa: E402
import eda_analysis  # noqa: E402
from insight_generator import detect_patterns  # noqa: E402
from genai_client import ask_claude  # noqa: E402

SUMMARY_SYSTEM_PROMPT = """You are writing the executive summary section of a business
report for e-commerce leadership. Given headline KPIs and detected patterns, write a
tight 4-6 sentence summary: overall health, the single most important pattern to act
on, and a one-line outlook. No bullet points, no numbers you weren't given."""


def build_report(data_dir: str) -> str:
    raw = etl_pipeline.extract(Path(data_dir))
    clean = etl_pipeline.transform(raw)
    order_value = eda_analysis.build_order_value_table(clean)

    sales = eda_analysis.sales_analysis(order_value, clean)
    cust = eda_analysis.customer_intelligence(clean, order_value)
    orders = eda_analysis.order_analysis(clean)
    reviews = eda_analysis.review_analysis(clean)
    facts = detect_patterns(clean, order_value)

    kpi_text = (
        f"Total revenue: R${sales['total_revenue']:,.2f} | "
        f"Delivered orders: {sales['total_orders_delivered']:,} | "
        f"AOV: R${sales['average_order_value']:.2f} | "
        f"Unique customers: {cust['total_customers']:,} | "
        f"Repeat rate: {cust['repeat_customer_rate_pct']}% | "
        f"Avg delivery: {orders['avg_delivery_days']} days | "
        f"Late rate: {orders['late_delivery_rate_pct']}% | "
        f"Avg review score: {reviews['avg_review_score']}/5"
    )
    facts_text = "\n".join(f"- ({f['area']}) {f['fact']}" for f in facts)

    summary = ask_claude(
        SUMMARY_SYSTEM_PROMPT,
        f"KPIs:\n{kpi_text}\n\nDetected patterns:\n{facts_text}",
        max_tokens=350,
    )

    report_date = date.today().isoformat()
    md = f"""# Customer Intelligence — Business Report
Generated: {report_date}

## Executive Summary
{summary}

## Key Performance Indicators
| Metric | Value |
|---|---|
| Total Revenue | R${sales['total_revenue']:,.2f} |
| Delivered Orders | {sales['total_orders_delivered']:,} |
| Average Order Value | R${sales['average_order_value']:.2f} |
| Unique Customers | {cust['total_customers']:,} |
| Repeat Customer Rate | {cust['repeat_customer_rate_pct']}% |
| Average Delivery Time | {orders['avg_delivery_days']} days |
| Late Delivery Rate | {orders['late_delivery_rate_pct']}% |
| Average Review Score | {reviews['avg_review_score']}/5 |

## Top Revenue Categories
{sales['top_10_categories_by_revenue'].head(5).to_markdown()}

## Detected Patterns This Period
{chr(10).join(f"- **{f['area']}**: {f['fact']}" for f in facts)}

---
*Report auto-generated by report_generator.py from the customer_intelligence pipeline.
All KPIs are computed directly from cleaned transaction data; narrative sections are
LLM-generated interpretation of those computed numbers.*
"""
    return md


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", required=True)
    parser.add_argument("--out", default="business_report.md")
    args = parser.parse_args()
    report = build_report(args.data_dir)
    Path(args.out).write_text(report)
    print(f"Report written to {args.out}")
